pygments: true
exclude: ["vendor"]
google_analytics_id: UA-50755011-1
github: {
  "hostname": "github.com",
  "pages_hostname": "github.io",
  "project_title": "john2x",
  "project_tagline": "john2x",
  "owner_name": "john2x",
  "owner_url": "https://github.com/john2x",
  "repository_url": "https://github.com/john2x/john2x.github.com",
  "url": "http://john2x.com"
}
